[2025-07-27T10:15:30.277+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-27T10:15:30.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_b scheduled__2025-07-26T00:00:00+00:00 [queued]>
[2025-07-27T10:15:31.163+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_b scheduled__2025-07-26T00:00:00+00:00 [queued]>
[2025-07-27T10:15:31.225+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-27T10:15:31.284+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalPythonOperator): ext_py_b> on 2025-07-26 00:00:00+00:00
[2025-07-27T10:15:31.452+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1205) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-27T10:15:31.494+0000] {standard_task_runner.py:64} INFO - Started process 1408 to run task
[2025-07-27T10:15:31.481+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_branch_operator', 'ext_py_b', 'scheduled__2025-07-26T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator.py', '--cfg-path', '/tmp/tmpjd7as81j']
[2025-07-27T10:15:31.670+0000] {standard_task_runner.py:91} INFO - Job 135: Subtask ext_py_b
[2025-07-27T10:15:32.306+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T10:15:33.747+0000] {task_command.py:426} INFO - Running <TaskInstance: example_branch_operator.ext_py_b scheduled__2025-07-26T00:00:00+00:00 [running]> on host 4112a2618ff3
[2025-07-27T10:15:35.674+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_operator' AIRFLOW_CTX_TASK_ID='ext_py_b' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-26T00:00:00+00:00'
[2025-07-27T10:15:35.720+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-27T10:15:43.516+0000] {baseoperator.py:400} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2025-07-27T10:15:44.937+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-callni685b6r/script.py /tmp/venv-callni685b6r/script.in /tmp/venv-callni685b6r/script.out /tmp/venv-callni685b6r/string_args.txt /tmp/venv-callni685b6r/termination.log
[2025-07-27T10:15:44.984+0000] {process_utils.py:187} INFO - Output:
[2025-07-27T10:16:06.888+0000] {process_utils.py:191} INFO - /home/***/.local/lib/python3.12/site-packages/***/configuration.py:815 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T10:16:06.892+0000] {process_utils.py:191} INFO - /home/***/.local/lib/python3.12/site-packages/***/configuration.py:741 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T10:16:06.898+0000] {process_utils.py:191} INFO - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T10:16:10.283+0000] {process_utils.py:191} INFO - /home/***/.local/lib/python3.12/site-packages/***/models/base.py:72 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T10:16:14.205+0000] {process_utils.py:191} INFO - Hello World from external Python
[2025-07-27T10:16:17.298+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-27T10:16:17.299+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-27T10:16:17.354+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_branch_operator, task_id=ext_py_b, run_id=scheduled__2025-07-26T00:00:00+00:00, execution_date=20250726T000000, start_date=20250727T101530, end_date=20250727T101617
[2025-07-27T10:16:17.560+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-07-27T10:16:17.784+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-27T10:16:17.807+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
